#
# Copyright 2021 The Sigstore Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: e2e-tests

# Run this workflow every time a new commit pushed to your repository
on: [push]

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  e2e-tests:
    # Name the Job
    name: Run tests
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16.3'
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: projectsigstore
          service_account_key: ${{ secrets.GCP_CI_SERVICE_ACCOUNT }}
          export_default_credentials: true
      - name: Install Crane
        run: go install github.com/google/go-containerregistry/cmd/crane
      - name: creds
        run: gcloud auth configure-docker us-central1-docker.pkg.dev --quiet
      - name: deps
        run: sudo apt-get update && sudo apt-get install -yq libpcsclite-dev
      - name: Run e2e tests that need secrets
        run: ./test/e2e_test_secrets.sh
